services:
  tests:
    build:
      context: ./
    environment:
      - CI
    volumes:
      - ./playwright-output:/app/playwright-output
      - ./tests:/app/tests
    ports:
      - 9323:9323
    ipc: host
