services:
  tests:
    build:
      context: ./
    tty: true
    environment:
      - CI=${CI}
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./tests/screenshots/actual:/app/tests/screenshots/actual
