name: Visual Tests
on:
  # デプロイされたときに実行
  deployment_status

jobs:
  screenshots:
    # Preview 環境へのデプロイが成功したときに実行
    if: github.event.deployment_status.environment == 'Preview' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    # Playwright が提供する Docker イメージ
    container:
      image: mcr.microsoft.com/playwright:v1.53.0-noble

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      # 本番環境でスクリーンショットを撮る
      - name: Take screenshots
        run: pnpm test:visual-update
        env:
          BASE_URL: https://noriapi.com/

      # Preview 環境でスクリーンショットを撮り、比較する
      - name: Visual tests
        run: pnpm test:visual
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
