name: "Handle Checkbox Changes"
on:
  issue_comment:
    types: [edited]

jobs:
  precheck:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: |
      github.event.issue.pull_request
      && github.event.issue.state == 'open'
      && startsWith(github.event.comment.body, '<!-- checkbox-workflow-action:managed -->')
      && github.actor == 'noriapi'
    outputs:
      continue: ${{ steps.check-checkbox.outputs.changed == 'true' && fromJSON(steps.check-checkbox.outputs.state).update-screenshots }}
      comment-id: ${{ steps.check-checkbox.outputs.comment-id }}
    steps:
      - name: Detect changes
        id: check-checkbox
        uses: wadackel/checkbox-workflow-action@v1
        with:
          id: vrt-command
          number: ${{ github.event.issue.number }}

      - name: Get comments
        uses: actions/github-script@v7
        with:
          script: |
            const { data } = await github.rest.issues.listComments({
              ...context.repo,
              issue_number: context.issue.number
            })

            core.debug(JSON.stringify(data, undefined, 4))

  main:
    needs: precheck
    runs-on: ubuntu-latest
    if: needs.precheck.outputs.continue == 'true'
    permissions:
      issues: write
      pull-requests: read
      contents: write
    steps:
      - name: Eyes Reaction
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ needs.precheck.outputs.comment-id }}
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: procces.env.COMMENT_ID,
              content: "eyes"
            })

      - name: Get data
        id: data
        uses: actions/github-script@v7
        with:
          script: |
            const pr = await github.rest.pulls.get({
              ...context.repo,
              pull_number: context.issue.number
            })
            setOutput("ref", pr.data.head.ref)

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.data.outputs.ref }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install partial dependencies
        run: pnpm install reg-cli

      - name: Take screenshots
        run: pnpm docker:test

      - name: Update screenshots
        run: pnpm test:visual-update

      - name: Commit & Push
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory $PWD
          git add "./tests/screenshots/expected"
          git commit -m "Update screenshots"
          git push

      - name: Add +1 Reaction
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ needs.precheck.outputs.comment-id }}
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: process.env.COMMENT_ID,
              content: "+1"
            })

      - name: Add -1 Reaction on Failure
        if: failure()
        uses: actions/github-script@v7
        env:
          COMMENT_ID: ${{ needs.precheck.outputs.comment-id }}
        with:
          script: |
            github.rest.reactions.createForIssueComment({
              ...context.repo,
              comment_id: process.env.COMMENT_ID,
              content: "-1"
            })
